spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 461200
server:
  port: 8190
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-locationa: classpath:mybatis-config.xml